// <auto-generated />
using System;
using Leilao.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Leilao.Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200727181701_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Leilao.Domain.Entities.ItemLeilao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("data_fim")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("data_inicio")
                        .HasColumnType("datetime");

                    b.Property<bool>("item_usado")
                        .HasColumnType("bit");

                    b.Property<string>("nome_leilao")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("nome_usuario")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<double>("valor_inicial")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("User");

                    b.ToTable("Leiloes");
                });

            modelBuilder.Entity("Leilao.Domain.Entities.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("usuario_ativo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("User");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
